# -*- coding: utf-8 -*-
"""loading the data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14VICr0wOSNQotESVeqIcRke_zhwAQdti

<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-33353-1660219050/blob/main/Application%20Building/loading%20the%20data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Team ID : PNT2022TMID08626

# Importing the required library
"""

import tensorflow

import numpy#for numerical analysis
import tensorflow#open source ml tool by google
from tensorflow.keras.datasets import mnist #mnist dataset
from tensorflow.keras.models import Sequential# stack for layers
from tensorflow.keras import layers#input,middle and output layers forcnn structure
from tensorflow.keras.layers import Dense,Flatten#dense and flatten layers
from tensorflow.keras.layers import Conv2D#convolutional layers
from tensorflow import keras#library for building neural networks built on tensorflow
from tensorflow.keras.optimizers import Adam#optimizers
from keras.utils import np_utils

"""# Loading the data"""

(x_train,y_train),(x_test,y_test)=mnist.load_data()

print(x_train.shape)
print(y_train.shape)

print(x_test.shape)
print(y_test.shape)